version: '3.8'

services:
  mindmap-app:
    build: .
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: Mount nginx logs
      - ./logs:/var/log/nginx