version: '3.8'

services:
  mindmap-app:
    build: .
    ports:
      - "3000:3001"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      # Database persistence
      - mindmap-data:/app/backend/data
      # Logs
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mindmap-data:
    driver: local